#!/data/data/com.termux/files/usr/bin/bash
pkg update -y && pkg upgrade
pkg install curl -y
pkg install proot -y

folder=ubuntu22jam-fs
dlink="https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/APT"
if [ -d "$folder" ]; then
	first=1
	echo "skipping downloading"
fi
tarball="ubuntu22jam-rootfs.tar.gz"

termux-setup-storage

if [ "$first" != 1 ];then
	if [ ! -f $tarball ]; then
		echo "Download Rootfs, this may take a while base on your internet speed."
		case `dpkg --print-architecture` in
		aarch64)
			archurl="arm64" ;;
		arm)
			archurl="armhf" ;;
		amd64)
			archurl="amd64" ;;
		x86_64)
			archurl="amd64" ;;
		*)
			echo "unknown architecture"; exit 1 ;;
		esac
		wget "https://github.com/wahasa/Ubuntu/releases/download/22.04/Ubuntu-22.04lts-${archurl}-jammy.tar.gz" -O $tarball

	fi

	cur=`pwd`
	mkdir -p "$folder"
	cd "$folder"
	echo "Decompressing Rootfs, please be patient."
	proot --link2symlink tar -xf ${cur}/${tarball} --exclude=dev||:
	cd "$cur"
fi

mkdir -p ubuntu22jam-binds
bin=ubuntu22jam
echo "writing launch script"
cat > $bin <<- EOM
#!/bin/bash
cd \$(dirname \$0)
## unset LD_PRELOAD in case termux-exec is installed
unset LD_PRELOAD
command="proot"
command+=" --kill-on-exit"
command+=" --link2symlink"
command+=" -0"
command+=" -r $folder"
if [ -n "\$(ls -A ubuntu22jam-binds)" ]; then
	for f in ubuntu22jam-binds/* ;do
		. \$f
	done
fi
command+=" -b /dev"
command+=" -b /proc"
command+=" -b /sys"
command+=" -b /data"
command+=" -b ubuntu22jam-fs/root:/dev/shm"
command+=" -b /proc/self/fd/2:/dev/stderr"
command+=" -b /proc/self/fd/1:/dev/stdout"
command+=" -b /proc/self/fd/0:/dev/stdin"
command+=" -b /dev/urandom:/dev/random"
command+=" -b /proc/self/fd:/dev/fd"
## uncomment the following line to have access to the home directory of termux
#command+=" -b /data/data/com.termux/files/home:/root"
command+=" -b /sdcard"
command+=" -w /root"
command+=" /usr/bin/env -i"
command+=" MOZ_FAKE_NO_SANDBOX=1"
command+=" HOME=/root"
command+=" PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games"
command+=" TERM=\$TERM"
command+=" LANG=en_US.UTF-8"
command+=" LC_ALL=C"
command+=" LANGUAGE=en_US"
command+=" /bin/bash --login"
com="\$@"
if [ -z "\$1" ];then
	exec \$command
else
	\$command -c "\$com"
fi
EOM

mkdir -p ubuntu22jam-fs/usr/share/andronix
mkdir -p ubuntu22jam-fs/var/tmp
rm -rf ubuntu22jam-fs/usr/local/bin/*

echo "127.0.0.1 localhost" > $folder/etc/hosts
echo "Set disable_coredump false" > $folder/etc/sudo.conf
wget -q https://raw.githubusercontent.com/tuanpham-dev/termux-ubuntu/master/.bash_profile -O ubuntu22jam-fs/root/.bash_profile > /dev/null
wget -q https://raw.githubusercontent.com/tuanpham-dev/termux-ubuntu/master/vnc -P ubuntu22jam-fs/usr/local/bin > /dev/null
wget -q https://raw.githubusercontent.com/tuanpham-dev/termux-ubuntu/master/vncpasswd -P ubuntu22jam-fs/usr/local/bin > /dev/null
wget -q https://raw.githubusercontent.com/tuanpham-dev/termux-ubuntu/master/vncserver-stop -P ubuntu22jam-fs/usr/local/bin > /dev/null
wget -q https://raw.githubusercontent.com/tuanpham-dev/termux-ubuntu/master/vncserver-start -P ubuntu22jam-fs/usr/local/bin > /dev/null
wget -q https://raw.githubusercontent.com/tuanpham-dev/termux-ubuntu/master/firstrun -P ubuntu22jam-fs/usr/share/andronix > /dev/null

chmod +x ubuntu22jam-fs/root/.bash_profile
chmod +x ubuntu22jam-fs/root/.profile
chmod +x ubuntu22jam-fs/usr/local/bin/vnc
chmod +x ubuntu22jam-fs/usr/local/bin/vncpasswd
chmod +x ubuntu22jam-fs/usr/local/bin/vncserver-start
chmod +x ubuntu22jam-fs/usr/local/bin/vncserver-stop

echo "fixing shebang of $bin"
termux-fix-shebang $bin
echo "making $bin executable"
chmod +x $bin
echo "removing image for some space"
rm $tarball

bash $bin

rm install-ubuntu22jam
